### author: Frish2021 ###
name: publish fire server.

on:
  workflow_dispatch:

jobs:
  build:
    name: Build NBT-jar
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: apply patches
        run: ./gradlew applyPatches

      - name: build paperclip jar
        run: ./gradlew createMojmapPaperclipJar

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          tag_name: 'Fire-1.21.1-R0.1-SNAPSHOT'
          name: 'Fire-1.21.1-R0.1-SNAPSHOT'
          files: 'build/libs/fire-paperclip-unspecified-mojmap.jar'
